version: "2"
services:
  web:
    image: docker_example
    # build: .
    # image: nbelov/docker_example:v1
    ports:
      - "4000:80"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/home/docker/data:/data"
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet:
